var arr =[
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more1.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more2.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more3.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more1.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more2.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more3.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more1.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more2.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more3.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more1.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more2.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more3.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more1.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more2.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more3.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more1.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more2.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more3.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more1.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more2.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more3.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more1.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more2.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more3.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more1.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more2.jpg"
	},
	{
		"title":"时尚宝宝小黄鸭T恤纯棉耐脏多色可选0-2岁宝宝",
		"price":"￥100.00",
		"photo":"http://www.ujchn.com/res/static/img/more3.jpg"
	}
]

var snap_data = [
	{
		"nowprice":"￥49.00",
		"pic":"http://www.ujchn.com/res/static/img/s_img2.jpg",
		"type":"宝宝五彩袜棉质舒服",
		"oldprice":"￥99.00"
	},
	{
		"nowprice":"￥49.00",
		"pic":"http://www.ujchn.com/res/static/img/s_img3.jpg",
		"type":"宝宝五彩袜棉质舒服",
		"oldprice":"￥99.00"
	},
	{
		"nowprice":"￥49.00",
		"pic":"http://www.ujchn.com/res/static/img/s_img4.jpg",
		"type":"宝宝五彩袜棉质舒服",
		"oldprice":"￥99.00"
	},
	{
		"nowprice":"￥49.00",
		"pic":"http://www.ujchn.com/res/static/img/s_img5.jpg",
		"type":"宝宝五彩袜棉质舒服",
		"oldprice":"￥99.00"
	},
	{
		"nowprice":"￥49.00",
		"pic":"http://www.ujchn.com/res/static/img/s_img2.jpg",
		"type":"宝宝五彩袜棉质舒服",
		"oldprice":"￥99.00"
	},
	{
		"nowprice":"￥49.00",
		"pic":"http://www.ujchn.com/res/static/img/s_img3.jpg",
		"type":"宝宝五彩袜棉质舒服",
		"oldprice":"￥99.00"
	}
]

var floor = [
	{
		"floor":"http://www.ujchn.com/res/static/img/s_img7.jpg"
	},
	{
		"floor":"http://www.ujchn.com/res/static/img/s_img8.jpg"
	},
	{
		"floor":"http://www.ujchn.com/res/static/img/s_img9.jpg"
	},
	{
		"floor":"http://www.ujchn.com/res/static/img/s_img10.jpg"
	},
	{
		"floor":"http://www.ujchn.com/res/static/img/s_img11.jpg"
	}
]







var list_data =[
	{
		"id":"1",
		"list_img":"http://www.ujchn.com/res/static/img/paging_img1.jpg",
		"list_pay":"1266",
		"list_price":"200",
		"list_title":"森系小清新四件套",
		"list_collect":"66"
	},
	{
		"id":"2",
		"list_img":"http://www.ujchn.com/res/static/img/paging_img2.jpg",
		"list_pay":"1200",
		"list_price":"210",
		"list_title":"森系小清新四件套",
		"list_collect":"626"
	},
	{
		"id":"3",
		"list_img":"http://www.ujchn.com/res/static/img/paging_img3.jpg",
		"list_pay":"1245",
		"list_price":"199",
		"list_title":"森系小清新四件套",
		"list_collect":"166"
	},
	{
		"id":"4",
		"list_img":"http://www.ujchn.com/res/static/img/paging_img1.jpg",
		"list_pay":"123",
		"list_price":"200",
		"list_title":"森系小清新四件套",
		"list_collect":"266"
	},
	{
		"id":"5",
		"list_img":"http://www.ujchn.com/res/static/img/paging_img2.jpg",
		"list_pay":"126",
		"list_price":"210",
		"list_title":"森系小清新四件套",
		"list_collect":"662"
	},
	{
		"id":"6",
		"list_img":"http://www.ujchn.com/res/static/img/paging_img3.jpg",
		"list_pay":"266",
		"list_price":"199",
		"list_title":"森系小清新四件套",
		"list_collect":"200"
	},
	{
		"id":"7",
		"list_img":"http://www.ujchn.com/res/static/img/paging_img1.jpg",
		"list_pay":"166",
		"list_price":"200",
		"list_title":"森系小清新四件套",
		"list_collect":"206"
	},
	{
		"id":"8",
		"list_img":"http://www.ujchn.com/res/static/img/paging_img2.jpg",
		"list_pay":"126",
		"list_price":"210",
		"list_title":"森系小清新四件套",
		"list_collect":"236"
	},
	{
		"id":"9",
		"list_img":"http://www.ujchn.com/res/static/img/paging_img3.jpg",
		"list_pay":"16",
		"list_price":"199",
		"list_title":"森系小清新四件套",
		"list_collect":"166"
	},
	{
		"id":"10",
		"list_img":"http://www.ujchn.com/res/static/img/paging_img1.jpg",
		"list_pay":"126",
		"list_price":"200",
		"list_title":"森系小清新四件套",
		"list_collect":"616"
	},
	{
		"id":"11",
		"list_img":"http://www.ujchn.com/res/static/img/paging_img2.jpg",
		"list_pay":"123",
		"list_price":"210",
		"list_title":"森系小清新四件套",
		"list_collect":"66"
	},
	{
		"id":"12",
		"list_img":"http://www.ujchn.com/res/static/img/paging_img3.jpg",
		"list_pay":"166",
		"list_price":"199",
		"list_title":"森系小清新四件套",
		"list_collect":"666"
	},
	{
		"id":"13",
		"list_img":"http://www.ujchn.com/res/static/img/paging_img1.jpg",
		"list_pay":"1886",
		"list_price":"200",
		"list_title":"森系小清新四件套",
		"list_collect":"686"
	},
	{
		"id":"14",
		"list_img":"http://www.ujchn.com/res/static/img/paging_img2.jpg",
		"list_pay":"1296",
		"list_price":"210",
		"list_title":"森系小清新四件套",
		"list_collect":"696"
	},
	{
		"id":"15",
		"list_img":"http://www.ujchn.com/res/static/img/paging_img3.jpg",
		"list_pay":"66",
		"list_price":"199",
		"list_title":"森系小清新四件套",
		"list_collect":"966"
	}
]





